# Generated by Django 4.1.7 on 2023-04-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('S_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
