# Generated by Django 4.1.7 on 2023-04-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Topic_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='S_no',
            new_name='Tid',
        ),
        migrations.AddField(
            model_name='topic',
            name='Age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Date',
            field=models.DateField(),
        ),
    ]
